// @generated by scripts/build-github-activity.mjs — do not edit by hand.
// Real GitHub activity, baked at build time. Public data (commits, repos) needs
// no token; the contribution calendar is populated only when GH_CONTRIB_TOKEN is
// set at build (0 / empty otherwise, so the panel shows repos, never a fake grid).
import type { Commit, ContributionCell } from "./types.js";

/** Recent commits read from the repos most recently pushed to, newest first. */
export const recentCommits: Commit[] = [
  {"hash":"31838e","message":"Updates","relativeTime":"4d ago","url":"https://github.com/Charlie-C-1266/my-portfolio/commit/31838e4b82e2bdc9978d550901483443884dbc43"},
  {"hash":"afce2f","message":"Updates","relativeTime":"4d ago","url":"https://github.com/Charlie-C-1266/my-portfolio/commit/afce2f0cdac463fffb65016a1582e64be6a1abe8"},
  {"hash":"139a17","message":"Updates","relativeTime":"4d ago","url":"https://github.com/Charlie-C-1266/my-portfolio/commit/139a17c175ece53499d017f1fc6aa4b059984eed"},
  {"hash":"e373bf","message":"Document the companion piledger-mcp server in the README (#175)","relativeTime":"5d ago","url":"https://github.com/Charlie-C-1266/PiLedger/commit/e373bf78a86b3f76d48327faee7b0ba248d9a341"},
  {"hash":"1d8536","message":"Add confirmation toasts for transaction actions (#174)","relativeTime":"5d ago","url":"https://github.com/Charlie-C-1266/PiLedger/commit/1d8536f634f5a9db117c8c4ee83f8f7256c98b3d"},
  {"hash":"2d41e0","message":"Add personal access token auth for headless clients","relativeTime":"6d ago","url":"https://github.com/Charlie-C-1266/PiLedger/commit/2d41e0382356ce6d42b048e23eb65ea131e66b42"},
];

/** Public repository count. */
export const publicRepoCount = 7;

/** Canonical GitHub profile URL. */
export const profileUrl = "https://github.com/Charlie-C-1266";

/** Real contributions in the last 12 months (0 until a build token is set). */
export const contributionTotal = 0;

/** Last ~15 weeks of real daily heat cells (empty until a build token is set). */
export const contributionCells: ContributionCell[] = [];

/** When this data was baked (ISO), for provenance. */
export const generatedAt = "2026-07-17T19:09:45.919Z";
