// @generated by scripts/build-blog-manifest.mjs — do not edit by hand.
// Rebuild with `npm run build:site` after adding or changing a post.
import type { Post } from "./types.js";

export const generatedPosts: Post[] = [
  {
    title: "Hello, world: how this blog works",
    blurb: "A quick tour of the write-in-Markdown, render-at-build-time flow that powers these posts.",
    date: "17 Jul 2026",
    readingTime: "2 min",
    url: "/blog/hello-world",
  },
];
